spring.application.name=apigateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true


spring.cloud.gateway.routes[0].id=rideservice
spring.cloud.gateway.routes[0].uri=lb://RIDESERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/ride/**

spring.cloud.gateway.routes[1].id=analyticsservice
spring.cloud.gateway.routes[1].uri=lb://ANALYTICSSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/analytics/**