spring.application.name=analyticsservice
server.port=8082

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ridelog_analytics_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.ridelog=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG

ride.service.url=${RIDE_SERVICE_URL:http://localhost:8081}

jwt.secret=${JWT_SECRET:6lFWwEC2tY1ZXBTRhu6q4en7XgyQW2tV+4iDU+mes54=}